### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by SylvainCorlay** [xtensor-stack/xtensor-fftw#47]
Hey @egpbos how about a new xtensor-fftw release?

I am happy to make the tag and update the recipes if you are ok with it.

**Comment by SylvainCorlay** [comment]
Note: I think we need to update the readme to say `xtensor >=0.20.10,<0.22` because it does work with 0.21...

**Comment by egpbos** [comment]
Yes, let's do a new release and fix the dependency description in the readme at the same time :) Would you like to do the honors?

**Comment by SylvainCorlay** [comment]
Closing as 0.2.6 was released!
